service: sls-vpc-example

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  versionFunctions: false
  logRetentionInDays: 1
  deploymentBucket:
    serverSideEncryption: AES256
  endpointType: regional

plugins:
  - serverless-vpc-plugin
  - serverless-webpack

package:
  individually: true
  excludeDevDependencies: true

custom:
  secretName: '${self:service}/${self:provider.stage}/rds'
  vpcConfig:
    cidrBlock: '10.0.0.0/16'
    createNatGateway: false
    createDbSubnet: true
    createNetworkAcl: false
    createFlowLogs: true
    createNatInstance: true
    createBastionHost: true
    bastionHostKeyName: philjr
    zones:
      - us-east-1a
      - us-east-1b
      - us-east-1c
    services:
      #- s3
  webpack:
    includeModules:
      forceExclude:
        - aws-sdk
    packager: npm

functions:
  rds:
    handler: index.handler
    description: RDS Test Handler
    role: ExampleLambdaRole
    environment:
      SECRET_NAME: ${self:custom.secretName}

resources:
  - ${file(resources/iam_cf.yml)}
  - ${file(resources/rds_cf.yml)}
  - ${file(resources/secretsmanager_cf.yml)}
