---
Resources:
  DBCluster:
    Type: 'AWS::RDS::DBCluster'
    Properties:
      DatabaseName: ${self:custom.databaseName}
      DBClusterIdentifier: '${self:service}-${self:provider.stage}'
      DBSubnetGroupName:
        Ref: RDSSubnetGroup
      EnableHttpEndpoint: true
      Engine: aurora-postgresql
      EngineMode: serverless
      EngineVersion: '10.7'
      MasterUsername:
        'Fn::Join':
          - ''
          - - '{{resolve:secretsmanager:'
            - Ref: DBSecret
            - ':SecretString:username}}'
      MasterUserPassword:
        'Fn::Join':
          - ''
          - - '{{resolve:secretsmanager:'
            - Ref: DBSecret
            - ':SecretString:password}}'
      StorageEncrypted: true
      Tags:
        - Key: Name
          Value:
            'Fn::Join':
              - '-'
              - - Ref: 'AWS::StackName'
                - rds

Outputs:
  DBClusterAddress:
    Description: RDS Cluster Address
    Value:
      'Fn::GetAtt':
        - DBCluster
        - 'Endpoint.Address'

  DBClusterPort:
    Description: RDS Cluster Port
    Value:
      'Fn::GetAtt':
        - DBCluster
        - 'Endpoint.Port'
