---
Resources:

  DBSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: ${self:custom.secretName}
      Description: 'RDS credentials for ${self:service}-${self:provider.stage}'
      GenerateSecretString:
        SecretStringTemplate: '{"username": "postgres"}'
        GenerateStringKey: password
        PasswordLength: 16
        ExcludeCharacters: '"@/\'

  SecretDBInstanceAttachment:
    Type: 'AWS::SecretsManager::SecretTargetAttachment'
    Properties:
      SecretId:
        Ref: DBSecret
      TargetId:
        Ref: DBInstance
      TargetType: 'AWS::RDS::DBInstance'
